services:

  api:
    build: ./backend
    env_file:
      - ./backend/.env
    restart: unless-stopped
    command: bun start
    ports:
      - "3000:3000"
    volumes:
      - zip_uploads:/tmp

  worker:
    build: ./backend
    env_file:
      - ./backend/.env
    restart: unless-stopped
    command: bun worker
    volumes:
      - zip_uploads:/tmp
      - static_hosting:/var/www/static-hosting

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./prod.Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/dist:/srv/frontend
      - caddy_data:/data
      - caddy_config:/config
      - static_hosting:/var/www/static-hosting

volumes:
  redis_data:
  caddy_data:
  caddy_config:
  zip_uploads:
  static_hosting:


