services:

  api:
    build: ./backend
    env_file:
      - .env
    restart: unless-stopped
    command: bun start
    ports:
      - "3000:3000"

  worker:
    build: ./backend
    env_file:
      - .env
    restart: unless-stopped
    command: bun worker

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./prod.Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/dist:/srv/frontend
      - caddy_data:/data
      - caddy_config:/config

volumes:
  redis-data:
  caddy_data:
  caddy_config:


